Add login with enter
Flexberry/ember-flexberry-account pull request #15
Opened 2023-09-26 10:29 UTC by TeterinaSvetlana

2023-09-27 05:40 UTC, neroslovegor approved these changes

2023-10-03 08:30 UTC, pepelyaeva requested changes

2023-10-03 08:30 UTC, pepelyaeva commented on addon/components/flexberry-login.js
> +      }
Надо вынести в именованную функцию и потом удалять обработчик с элемента

2023-10-04 12:58 UTC, DubrovinPavel approved these changes

2023-10-04 12:58 UTC, pepelyaeva approved these changes

2023-10-04 13:26 UTC, merged